config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :models
  resources :categories, only:[:index,:show,:edit,:update]
  resources :products, only:[:show,:edit,:update]

  get "cart" => "cart#show"
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout

  match '/shop',    to: 'static_pages#shop',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/pros', to: 'static_pages#pros', via: 'get'
  match '/our_advantages', to: 'static_pages#our_advantages', via: 'get'


 root 'static_pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	 
	 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :model

  scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
  scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}

  COMPLETE = "complete"
  IN_PROGRESS = "in_progress"

  def self.find_with_product(product)
    return [] unless product
    complete.joins(:line_items).
        where(["line_items.product_id = ?", product.id]).
        order("orders.checked_out_at DESC")
  end

  def checkout!
    self.checked_out_at = Time.now
    self.save
  end

  def recalculate_price!
    self.total_price = line_items.inject(0.0){|sum, line_item| sum += line_item.price }
    save!
  end

 

  def display_name
    ActionController::Base.helpers.number_to_currency(total_price) +
        " - Order ##{id} (#{model.email})"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
 
   has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :category
 
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin
 
  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
 protect_from_forgery prepend: true

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_model!
  before_action :find_cart

  def add
    @cart.save if @cart.new_record?
    session[:cart_id] = @cart.id
    product = Product.find(params[:id])
    LineItem.create! :order => @cart, :product => product, :price => product.price
    @cart.recalculate_price!
    flash[:notice] = "Item added to cart!"
    redirect_to '/cart'
  end

  def remove
    item = @cart.line_items.find(params[:id])
    item.destroy
    @cart.recalculate_price!
    flash[:notice] = "Item removed from cart"
    redirect_to '/cart'
  end

  def checkout
    @cart.checkout!
    session.delete(:cart_id)
    flash[:notice] = "Thank you for your purchase! We will ship it shortly!"
    redirect_to "/"
  end

  protected

  def find_cart
    @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_model.orders.build
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def show

	@category=Category.find(params[:id])
	@products=Product.where(category_id: @category.id)
	if current_admin_user !=nil
	@orders=[]
	@products.each do |product|
		

	end

	else
	@orders=nil
	end
end

def edit
	@category=Category.find(params[:id])
end

def update
	@category=Category.find(params[:id])
    @category.update(cat_params)
end

private
def cat_params
params.require(:category).permit(:name,:description,:image)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



	def show
		@product=Product.find(params[:id])

        @products = Product.all
	end

	def edit
		@product=Product.find(params[:id])
	end

	def update
		@product=Product.find(params[:id])
		@product.update(product_params)
	end

private
	def product_params
		params.require(:product).permit(:name,:description,:image)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def shop
    @categories=Category.all
  end

  def contact
  end

  def about
  end

  def add_car
  end

  def profile_info
  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cart/show.html.erb
  <style>
html, body{margin:0;padding:0; width:100%;}
      </style>
      <hr>
<h1>Мій кошик:</h1>
<hr>
<% unless @cart.line_items.any? %>
  <p>Ваш кошик порожній => <%= link_to "Магазин", shop_path %>
<% end %>

<table width="100%">
  <tr>
    <th>Позиція</th>
    <th>Ціна</th>
  </tr>
  <% for line_item in @cart.line_items %>
    <tr>
      <td><%= line_item.product.name %></td>
      <td><%= number_to_currency line_item.price %></td>
      <td><%= link_to "Видалити", remove_from_cart_path(line_item), :method => :post %></td>
    </tr>
  <% end %>
  <tr>
    <td>Загалом:</td>
    <td><%= number_to_currency @cart.total_price %></td>
  </tr>
</table>

<hr />
<%= form_tag checkout_path, :style => "text-align: right" do |f| %>
  <%= link_to "Продовжити покупку!", root_path %>
  або
  <%= submit_tag "Підтвердити!" %>
<% end %>

app/views/categories/show.html.erb
 <hr>
<div class="on">
	<%= @category.name %>
</div>
<hr>
<%@products.each do |product|%>
<%= render 'products/elem',product:product %>
<%end%>
	<p align="center"> <%= link_to "Повернутися до категорій", shop_path %> </p>
	

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
 <strong>© 2018 ELBIKES. Спеціалізований магазин, де можна купити електрбайки, а також аксесуари та запчастини до них.</strong>
</small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <div class="section-inner">
      <div class="logo">ELBIKES.COM.UA</div>
    </div>
  </div>

  <input type="checkbox" id="dws-menu">
  <div class="leb-menu">
    <label for="dws-menu"><img src="assets/icono-menu.png"></label>
  </div>
  <!-- nav -->
  <nav class="menu">
    <div class="section-inner indents">
      <ul>
         <li><%= link_to "Головна", root_path %></li>  
           <li><%= link_to "Магазин", shop_path %></li>
        <li><%= link_to "Тест-драйв", our_advantages_path %></li>
        <li><%= link_to "Мій кошик", cart_path %></li>
<li> <%= link_to "Авторизація", new_model_registration_path %></li>
        <li><%= link_to "Контакти", contact_path %></li>
      </ul>
    </div>
  </nav><!--/nav-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/orders/orders.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/_elem.html.erb
<div class="container">
		<div class="container-fluid text-center bg-grey">
			<div class="col-lg-4">
				<div class="thumbnail">

					<p><strong><h3 style="color: #0772A1;"></h3></strong></p>
					<div class="img">
					<img src="<%=product.image_file_name%>" width="400" height="400">
                    </div>
					<h3><%= product.name %></h3>
					

<h4>Ціна: <span style="color: green;"><%= product.price %> $</span></h4>
  
<div class="cart-btnn">
        <h5><%= link_to "Детальніше", product %></h5>
 </div>

				</div>
			
			</div>
		
		</div>
		
	</div>
<hr>

app/views/products/show.html.erb
  <style>
html, body{margin:0;padding:0; width:100%;}
      </style>
<main class="container1">
 
<!-- Left Column / Headphones Image -->
  <div class="img">
<img src="<%=@product.image_file_name%>" width="400" height="400" alt="Product picture">
  </div>
 
 
  <!-- Right Column -->
  <div class="right-column">
 
    <!-- Product Description -->
    <div class="product-description">
      <span>Product:</span>
      <h3><%=@product.name %></h3>
      <p><%=@product.description%></p>
    </div>
    
 
    <!-- Product Pricing -->
    <div class="product-price">
     <span>Ціна: <%=@product.price %> $</span>
      <div class="cart-btn">
      <%= link_to "Замовити", add_to_cart_path(@product.id) %>
      </div>
    </div>
    </div>
</main>

app/views/static_pages/about.html.erb
  <style>
html, body{margin:0;padding:0; width:100%;}
      </style>
<hr>
<center><img src="https://images.ua.prom.st/740722714_w640_h2048_snimok_ekrana___25_v_20.09.jpg?PIMAGE_ID=740722714"></center><hr>
<p class="lead"><i>Деякі відвідувачі нашого магазину, вперше побачивши 
електроскутери типу CityCoco і дізнавшись їх ціну, відразу обурюються: 
«Навіщо мені платити 800$ і більше, коли бензиновий б/в скутер з 
двигуном 50 кубиків коштує від 300$?». Ми намагаємося пояснити нашим 
клієнтам, що купуючи будь-який бензиновий скутер і користуючись ним 
кілька років, вони значно переплатять.</p>
<h2>1) Економія на паливі</h2>
<hr>
<p><i>Мінімальну витрату 2 літрів палива на 100 км можна отримати тільки на
 нових брендових скутерах типу Honda Dio в режимі їзди без розгонів і 
гальмувань на швидкості 30 км/год. Витрата по місту буде мінімум 3 
літри, якщо їздити спокійно і мотор в хорошому стані. З огляду на їзду в
 холодну пору доби, поїздки на короткі дистанції, поїздки з другим 
пасажиром, витрата зростає до 4 л на 100 км. Разом, кожні 100 км шляху 
будуть обходитися мінімум в 4$.</p>
<p>Якщо середній пробіг становить 15 км на день, то за рік це буде 
близько 5500 км, а за 3 роки - 16500 км. Це умовний розрахунок, в якому 
ми не враховуємо зимовий період. При такому пробігу тільки на паливо ви 
витратите 660$. Вам дуже пощастить, якщо не доведеться ремонтувати 
двигун, не кажучи про інші поломки.</p>
<p>У випадку з електроскутером витрати не електрику просто мізерні, на 
одну зарядку 20 А/Год акумулятора витрачається всього 1,5 кВт 
електроенергії. Навіть при найвищому тарифі елеткроенергії і при 
максимально швидкій, агресивній їзді ви витрачатимете близько 0,25$ на 
100 км. Це 41$ за 3 роки при пробігу 16500 км. Реально ж, при спокійній 
їзді і звичайному домашньому тарифі електроенергії за цей період витрати
 будуть 15-20$.</p>
<p><b>Економія на паливі складе приблизно 600$.</b></p>
<h2>2) Економія на запчастинах</h2>
<hr>
<p>У електроскутера практично немає елементів, що труться, навіть у 
самому моторі. При стандартних умовах експлуатації зношуються тільки 
гальмівні колодки, диски і підшипники.</p>
<p>Навіть не рахуючи витрати на обслуговування і заміну запчастин, 
враховуючи вартість бензинового б/в скутера біля 300$, ви могли б за 
зекономлені гроші купити НОВИЙ електроскутер замість б/в бензинового 
мопеда. Якщо ж пробіг у два рази більше, то за три роки ви витратите на 
бензин і обслуговування більше грошей, ніж коштує найпотужніший і 
наворочений електроскутер, наприклад, CityCoco Harley.</p>
<p>Наші клієнти часто говорять: «В електроскутері потрібно міняти акумулятор». Так, звичайно потрібно. Але:</p>
<p>1) Найдешевша батарея на 60В 12 Ah забезпечує мінімум 25000 км 
пробігу. Це в умовах агресивної їзди зі швидкими прискореннями, з одним 
або навіть двома пасажирами та іншими додатковими навантаженнями. При 
щадній експлуатації пробіг становитиме 50-70 тис км. Для більш ємних 
батарей, наприклад 20 а.год, яка коштує трохи дорожче, пробіг зростає 
пропорційно ємності.</p>
<p>2) 12 Ah батарея коштує не дорожче нового двигуна на бензиновий 
скутер. Звичайно ж, набагато простіше поміняти батарею на 
електроскутері, ніж робити капіталку або міняти двигун на бензиновому 
мопеді. Тим більше, що є варіант здешевити заміну батареї, самостійно 
замінивши в ній елементи, типу 18650.</p>
<p>3) Бензиновий двигун легко може бути перегрітий і зіпсований від 
високих обертів, їзди в натяг та інших чинників, які не страшні 
електродвигуну.</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta id="viewport" name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
<meta charset="utf-8">
<meta name="Keywords" content="cssplay, css, play, cascading, style, sheets, responsive, Slider, slideshow, picture, Font, Awesome">
<meta name="Description" content="CSS play - Responsive 'Swiper' slideshow with html5 picture and Font Awesome">
 
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet"> 
 
<style>
/* general styling */
html, body{margin:0;padding:0; width:100%;}
.wrapper {width:75%; max-width:1000px; margin:100px auto -100px auto;}
.wrapper h1.cssplay {margin:0; padding:0; color:#2ab; font:300 50px/60px 'Lato', sans-serif;}
.wrapper h1.cssplay a {color:#2ab; text-decoration:none;}
.wrapper h2.title {margin:0; padding:10px 0; color:#444; font:300 20px/30px 'Lato', sans-serif;}
.wrapper h2.title a {color:#2ab; text-decoration:none;}
.wrapper h3.date {margin:0; padding:0; color:#000; font:300 16px/25px 'Lato', sans-serif;}
.wrapper h2.info {margin:0; padding:0; color:#000; font:300 30px/40px 'Lato', sans-serif;}
.wrapper p {margin:0; padding:8px 0; color:#000; font:300 20px/30px 'Lato', sans-serif;}
.wrapper p a {color:#2ab; text-decoration:none;}
.download {display:inline-block; width:200px; background:#080; border-radius:5px;  font:300 20px/30px 'Lato', sans-serif; color:#fff; text-decoration:none; padding:10px; white-space:nowrap;}
</style>

<style>
/* swiper styling */
.swiper-container{width:100%; background:#fff; margin:50px 0;}
.swiper-slide{text-align:center;background:#fff;display:-webkit-box;display:-ms-flexbox;display:-webkit-flex;display:flex;-webkit-box-pack:center;-ms-flex-pack:center;-webkit-justify-content:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;-webkit-align-items:center;align-items:center;}
picture {width:calc(100% - 60px); padding-bottom:40px;}
picture img {display:block; width:100%;}
.swiper-pagination span {width:20px; height:20px; background:#c60; font-size:15px; color:#fff; transition:0.5s;}
.swiper-pagination span:hover {opacity:1;}
.swiper-button-prev-icon {position:absolute;top:0;width:31px; left:-1px; height:100%;margin-top:-22px;z-index:10;cursor:pointer; font-size:60px; text-align:center; background:#fff; color:#c60; display:flex; flex-direction:column; flex-wrap:nowrap; justify-content:center;}
.swiper-button-next-icon {position:absolute;top:0; right:-1px;width:31px;height:100%;margin-top:-22px;z-index:10;cursor:pointer;font-size:60px; text-align:center; background:#fff; color:#c60; display:flex; flex-direction:column; flex-wrap:nowrap; justify-content:center;}
.swiper-container section {position:absolute; left:30px; top:0; width:calc(100% - 60px); height:calc(100% - 50px); background:url(swiper-images/bg-grid.png); background-attachment:fixed; text-align:center;}
.swiper-container h1 {margin:0; padding:0; color:#fff; font:300 50px/70px 'Lato', sans-serif;}
.swiper-container p {margin:0; padding:0; color:#fff; font:400 20px/30px 'Lato', sans-serif; position:absolute; bottom:20px; left:0; width:100%;}
@media only screen and (max-width: 640px) {
  .swiper-container h1 {font:300 40px/55px 'Lato', sans-serif;}
  .swiper-container p {font:400 18px/22px 'Lato', sans-serif;}
}
@media only screen and (max-width: 480px) {
  .swiper-button-prev-icon {display:none;}
  .swiper-button-next-icon {display:none;}
  picture {width:100%;}
  .swiper-container section {left:0; width:100%;}
  .swiper-container h1 {font:300 30px/40px 'Lato', sans-serif;}
  .swiper-container p {font:400 15px/20px 'Lato', sans-serif;}
  .swiper-container section {width:100%;}
}
</style>
</head>
<body>


<div class="wrapper" onclick="">
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <picture>
        <source srcset="https://pp.userapi.com/c837733/v837733633/39807/vPLovTk0CBY.jpg" media="(max-width: 320px)">
        <source srcset="assets/pic1b.jpg" media="(max-width: 640px)">
        <source srcset="https://cdn.shopify.com/s/files/1/1950/4033/products/SCR_SIdeshot_wShadow_BrandBlue_mStr_2048x2048.png?v=1495192375">
        <img src="assets/pic1a.jpg" alt="My default image">
      </picture>
      <section>
        <h1></h1>
      </section>
    </div>
    <div class="swiper-slide">
      <picture>
        <source srcset="https://pp.userapi.com/c837733/v837733633/39807/vPLovTk0CBY.jpg" media="(max-width: 320px)">
        <source srcset="assets/pic2b.jpg" media="(max-width: 640px)">
        <source srcset="https://cdn.shopify.com/s/files/1/1950/4033/products/SCR_SIdeshot_wShadow_Pitchblack_oStr_2048x2048.jpg?v=1498135355">
        <img src="assets/pic2a.jpg" alt="My default image">
      </picture>
      <section>
        <h1></h1>
      </section>
    </div>
    <div class="swiper-slide">
      <picture>
        <source srcset="https://pp.userapi.com/c837733/v837733633/39807/vPLovTk0CBY.jpg" media="(max-width: 320px)">
        <source srcset="assets/pic3b.jpg" media="(max-width: 640px)">
        <source srcset="https://cdn.shopify.com/s/files/1/1950/4033/products/SCR_SIdeshot_wShadow_FoamWhite_oStr_2048x2048.jpg?v=1498135528">
        <img src="assets/pic3a.jpg" alt="My default image">
      </picture>
      <section>
        <h1></h1>
      </section>
    </div>
    <div class="swiper-slide">
      <picture>
        <source srcset="https://pp.userapi.com/c837733/v837733633/39807/vPLovTk0CBY.jpg" media="(max-width: 320px)">
        <source srcset="assets/pic4b.jpg" media="(max-width: 640px)">
        <source srcset="https://cdn.shopify.com/s/files/1/1950/4033/products/SCR_SIdeshot_wShadow_Pitchblack_oStr_2048x2048.jpg?v=1498135355">
        <img src="assets/pic4a.jpg" alt="My default image">
      </picture>

    </div>
  </div>
  <div class="swiper-pagination"></div>
  <div class="swiper-button-next-icon"><i class="fa fa-angle-right"></i></div>
  <div class="swiper-button-prev-icon"><i class="fa fa-angle-left"></i></div>
</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"></script>
 
<script>
  var mySwiper = new Swiper ('.swiper-container', {
    loop: true,
    keyboardControl: true,
    pagination: '.swiper-pagination',
    paginationBulletRender: function (swiper, index, className) {
      return '<span class="' + className + '"><i class="fa fa-angle-up"></i></span>';
    },
    paginationClickable: true,
    spaceBetween: -30,
    breakpoints: {
    480: {
      spaceBetween: 30
      }
    },
    nextButton: '.swiper-button-next-icon',
    prevButton: '.swiper-button-prev-icon',
    autoplay:6000,
    autoplayDisableOnInteraction:false,
    speed:1000,
    grabCursor:true,
    roundLengths: true
  });
</script>

















<div class="body-content">
  <div class="section-inner">
<br>
<hr>
<h1>SEEV CITYCOCO - стильно , модно , економічно !</h1>
<hr>
    <!-- news-list -->
    <div class="news-list">
      <!-- one-news -->
      <div class="one-news mobile">
       <center> <img src="http://www.platform.in.ua/wp-content/uploads/2015/12/GARANTIYA-YAKOSTI.png" alt="Pros"> </center>
       <br>
       <br>
       <br>
       <br>
      
        <h2>Чому саме ми ?</h2>
       <center><h4><%= link_to "Гарантія.Якість.Обслуговування", pros_path %></h4></center>
      </div><!--/one-news-->

      <!-- one-news -->
      <div class="one-news one-news-second mobile">
        <img src="assets/bike.jpg" alt="Bike">
        <h2>Оберіть бажану комплектацію</h2>
        <center><h4><%= link_to "в нашому магазині !", shop_path %></h4></center>
      </div><!--/one-news-->

      <!-- one-news -->
     <!--  <div class="one-news one-news-last mobile">
        <center><img src="https://images.ua.prom.st/740722714_w640_h2048_snimok_ekrana___25_v_20.09.jpg?PIMAGE_ID=740722714" alt="Bike"></center>
        <h2  >Чому обирають SEEV CITYCOCO ?</h2>
        <hr>
        <center><h4><%= link_to "Дізнатись !", about_path %><h4></center>
      </div><!--/one-news-->

    </div><!--/news-list-->

  </div>
</div><!--/body-content-->
 <br>
       <br>
       <br>
       <br> 
       <br>
       <br>
       <br> 
       <br>
       <br>
       <br> 
       <br>
       <br>
       <br> 
       <br>
       <br>
       <br> 
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
       <br>
</body>
</html>

app/views/static_pages/our_advantages.html.erb
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Чому обирають саме нас ?</title>
      <style>
html, body{margin:0;padding:0; width:100%;}
      </style>
 </head>
 <body>
 <br>
 <div class="onn">Безкоштовний тест-драйв !</div>
 <hr>
  <p><img src="https://images-na.ssl-images-amazon.com/images/I/51F9IPvmOKL.jpg" alt="" width="400" height="400" class="leftimg"></p>
 <i>    
<h2>Ми пропонуємо нашим клієнтам безкоштовний тест-драйв для того , щоб вони змогли переконатися в якості наших Seev Citycoco !</h2>
<h2>Технічні характеристики Seev Citycoco:</h2>
<li>Загальна вага - 55 кг</li>
<li>Максимальна швидкість - до 50 км/год</li>
<li>Запас ходу - до 80 км</li>
<li>Мотор - 1000W (50H)</li>
<li>Тормоза - дискові(гідравлічні)</li>
<li>Акумулятор LiIon - 12aH/60V</li>
<li>Ємність - 12aH</li>
<li>Напруга - 60V</li>
<li>Передні/задні амортизатори</li>
<li>Цифровий спідометр</li>
<h2>Запис на тест-драйв по тел. +38(066)406-12-79</h2>
<br><br><br><br><br><br><br><br>
 </body>
</html>

app/views/static_pages/shop.html.erb
  <style>
html, body{margin:0;padding:0; width:100%;}
      </style>

<hr>
<div class="onn">Оберіть категорію</div>
<br>
<hr>



<div id="wrapper">
	<%@categories.each do |category|%>
	 <div class="section">
			
  			<p><strong><div class="on">
				<b><%= link_to category.name, category_path(category.id) %></b>
				<hr>
				<center>
				<img src="<%=category.image_file_name%>" width="300" height="300">
				</div></strong></p>
			</center>
			</div>
	<%end%>
</div>
<br><br><br><br><br><br><br><br>